[build-system]
requires = ["setuptools>=58.0.0", "wheel", "briefcase"]
build-backend = "briefcase.app"

[tool.briefcase]
project_name = "voice_activated_chat_system"
formal_name = "Voice Activated Chat System"
application_id = "com.example.voiceassistant"  # Placeholder or generic application identifier
version = "0.1.0"
description = "A voice-activated personal assistant designed to interact and analyze speech, incorporating advanced NLP and ML capabilities."
authors = [{name = "Ant Greene", email = "Reel0112358.13@proton.me"}]
url = ""  # Intentionally left blank
license = "MIT"

[tool.briefcase.app.voice_activated_chat_system]
icon = "icons/windows/icon.ico"
requires = [
  "toga>=0.3.0.dev26",
  "cryptography>=3.4",
  "spacy>=3.0",
  "nltk>=3.6",
  "pyttsx3>=2.90",
  "SpeechRecognition>=3.8",
  "transformers>=4.5",
  "aiosqlite>=0.17.0",
  "huggingface_hub>=0.1.0",
  "beautifulsoup4>=4.9.3",
  "requests>=2.25",
  "python-dateutil>=2.8.1",
  "bs4",  # Alias for beautifulsoup4
  "logging"  # Note: logging is part of the Python Standard Library and does not require installation
]
sources = [
  "voice-activated-assistant/"
]

[tool.briefcase.app.voice_activated_chat_system.windows]
python_version = "3.9"