name: Build and Deploy Voice-Activated Chat System for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Python and Create virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m venv venv
        working-directory: voice-activated-assistant

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build application
        run: |
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          briefcase build windows
          briefcase package windows
        working-directory: voice-activated-assistant

      - name: Deactivate virtual environment
        run: deactivate
        working-directory: voice-activated-assistant

      - name: Clean up cache
        run: |
          git clean -ffdx
          rm -rf venv/
        working-directory: voice-activated-assistant

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: voice-activated-assistant/windows/dist/*.msi