name: Build and Deploy Voice-Activated Chat System for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Execute deploy script
        run: |
          ./deploy.sh
        working-directory: ${{github.workspace}}/voice-activated-assistant
        shell: bash

      - name: Build Executable with PyInstaller
        run: |
          .\venv\Scripts\activate
          pyinstaller --onefile --windowed main.py
        working-directory: ${{github.workspace}}/voice-activated-assistant

      - name: Cleanup
        run: |
          deactivate
          git clean -ffdx --exclude='!venv/'
        working-directory: ${{github.workspace}}/voice-activated-assistant

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: ${{github.workspace}}/voice-activated-assistant/dist/main.exe