name: Build and Deploy Voice-Activated Chat System for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Briefcase
        run: pip install briefcase

      - name: Create and build Windows application
        run: |
          cd voice-activated-assistant
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: windows/voice-activated-assistant/dist/*.msi