name: Build Voice-Activated Chat System Executable

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toga spacy nltk pyttsx3 cryptography SpeechRecognition

    - name: Install additional dependencies
      run: |
        pip install huggingface_hub  # if transformers are used in the project

    - name: Download NLP models
      run: |
        python -m spacy download en_core_web_trf
        python -m nltk.downloader punkt

    - name: Create Executable
      run: |
        pyinstaller --onefile --clean --add-data "voice-activated-assistant/*.py;voice-activated-assistant" voice-activated-assistant/main.py
      # Adjust the add-data path if your source files are located in a different folder

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: voice-activated-chat-system-executable
        path: dist/*.exe