name: Build and Deploy Voice-Activated Chat System for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: voice-activated-assistant

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment and activate
        run: |
          python -m venv venv
          .\venv\Scripts\activate

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: voice-activated-assistant

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and package application using PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icons/windows/icon.ico main.py

      - name: Deactivate virtual environment and clean up cache
        run: |
          deactivate
          git clean -ffdx
          rm -rf venv/

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/main.exe