name: Build and Deploy Voice-Activated Chat System for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'voice-activated-assistant/**'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: python -m venv venv
        working-directory: voice-activated-assistant

      - name: Activate virtual environment
        run: |
          .\venv\Scripts\activate
          pip install --upgrade pip
        working-directory: voice-activated-assistant

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: voice-activated-assistant

      - name: Build and Package Windows application
        run: |
          briefcase build windows
          briefcase package windows
        working-directory: voice-activated-assistant

      - name: Deactivate virtual environment
        run: deactivate
        working-directory: voice-activated-assistant

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: voice-activated-assistant/windows/dist/*.msi